{% set name = "coin-or-cgl" %}
{% set version = "0.60.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coin-or/Cgl/archive/releases/{{ version }}.tar.gz
  sha256: 558421ccd6aa91d6922dd1baa04e37aa4c75ba0472118dc11779e5d6a19bfb38
  patches:
    - 0001-Patch-for-downstream.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make  # [unix]
  host:
    - coin-or-utils
    - coin-or-osi
    - coin-or-clp
    - libblas
    - libcblas
    - liblapack
    - zlib
    - bzip2
    - ncurses
    - readline
  run:
    - ncurses
    - readline
  run_constrained:
    - coincbc * *_metapackage

test:
  commands:
    - test -f $PREFIX/lib/libCgl${SHLIB_EXT}
    - test -f $PREFIX/include/coin/CglAllDifferent.hpp

about:
  home: https://projects.coin-or.org/Cgl
  dev_url: https://github.com/coin-or/Cgl
  license: EPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: COIN-OR Cut Generation Library (Cgl)
  description: |
    The COIN-OR Cut Generation Library (Cgl) is a collection of cut generators
    that can be used with other COIN-OR packages that make use of cuts, such as,
    among others, the linear solver Clp or the mixed integer linear programming
    solvers Cbc or BCP. Cgl uses the abstract class OsiSolverInterface (see Osi)
    to use or communicate with a solver. It does not directly call a solver.

extra:
  recipe-maintainers:
    - wolfv
    - tkralphs
